export const fake_arr = [
  {
    id: 1,
    name: "Leo",
    image: "https://source.unsplash.com/random?query=geography&count=1",
    price: "100",
    rating: "4.5",
    review_count: "100",
    location: "San Francisco, CA",
    lat: "37.7749",
    lng: "-122.4194",
    url: "https://www.airbnb.com/rooms/146059113",
    host_name: "John",
    host_image:
      "https://a0.muscache.com/im/users/146059113/profile_pic/146059113/original.jpg?aki_policy=profile_x_medium",
    host_url: "https://www.airbnb.com/users/show/146059113",
    host_location: "San Francisco, CA",
  },
  {
    id: 2,
    name: "John",
    image: "https://source.unsplash.com/random?query=geography&count=2",
    price: "100",
    rating: "4.5",
    review_count: "100",
    location: "San Francisco, CA",
    lat: "37.7749",
    lng: "-122.4194",
    url: "https://www.airbnb.com/rooms/146059113",
    host_name: "John",
    host_image:
      "https://a0.muscache.com/im/users/146059113/profile_pic/146059113/original.jpg?aki_policy=profile_x_medium",
    host_url: "https://www.airbnb.com/users/show/146059113",
    host_location: "San Francisco, CA",
  },
  {
    id: 3,
    name: "Alex",
    image: "https://source.unsplash.com/random?query=geography&count=3",
    price: "100",
    rating: "4.5",
    review_count: "100",
    location: "San Francisco, CA",
    lat: "37.7749",
    lng: "-122.4194",
    url: "https://www.airbnb.com/rooms/146059113",
    host_name: "John",
    host_image:
      "https://a0.muscache.com/im/users/146059113/profile_pic/146059113/original.jpg?aki_policy=profile_x_medium",
    host_url: "https://www.airbnb.com/users/show/146059113",
    host_location: "San Francisco, CA",
  },
  {
    id: 4,
    name: "George",
    image: "https://source.unsplash.com/random?query=geography&count=4",
    price: "100",
    rating: "4.5",
    review_count: "100",
    location: "San Francisco, CA",
    lat: "37.7749",
    lng: "-122.4194",
    url: "https://www.airbnb.com/rooms/146059113",
    host_name: "John",
    host_image:
      "https://a0.muscache.com/im/users/146059113/profile_pic/146059113/original.jpg?aki_policy=profile_x_medium",
    host_url: "https://www.airbnb.com/users/show/146059113",
    host_location: "San Francisco, CA",
  },
  {
    id: 5,
    name: "Daniel",
    image: "https://source.unsplash.com/random?query=geography&count=5",
    price: "100",
    rating: "4.5",
    review_count: "100",
    location: "San Francisco, CA",
    lat: "37.7749",
    lng: "-122.4194",
    url: "https://www.airbnb.com/rooms/146059113",
    host_name: "John",
    host_image:
      "https://a0.muscache.com/im/users/146059113/profile_pic/146059113/original.jpg?aki_policy=profile_x_medium",
    host_url: "https://www.airbnb.com/users/show/146059113",
    host_location: "San Francisco, CA",
  },
  {
    id: 6,
    name: "Ben",
    image: "https://source.unsplash.com/random?query=geography&count=6",
    price: "100",
    rating: "4.5",
    review_count: "100",
    location: "San Francisco, CA",
    lat: "37.7749",
    lng: "-122.4194",
    url: "https://www.airbnb.com/rooms/146059113",
    host_name: "John",
    host_image:
      "https://a0.muscache.com/im/users/146059113/profile_pic/146059113/original.jpg?aki_policy=profile_x_medium",
    host_url: "https://www.airbnb.com/users/show/146059113",
    host_location: "San Francisco, CA",
  },
  {
    id: 7,
    name: "Leonard",
    image: "https://source.unsplash.com/random?query=geography&count=7",
    price: "100",
    rating: "4.5",
    review_count: "100",
    location: "San Francisco, CA",
    lat: "37.7749",
    lng: "-122.4194",
    url: "https://www.airbnb.com/rooms/146059113",
    host_name: "John",
    host_image:
      "https://a0.muscache.com/im/users/146059113/profile_pic/146059113/original.jpg?aki_policy=profile_x_medium",
    host_url: "https://www.airbnb.com/users/show/146059113",
    host_location: "San Francisco, CA",
  },
];
const booking_desc_1 =
  "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum";
const booking_desc = `${booking_desc_1} ${booking_desc_1}`;
export const my_bookings = [
  {
    id: 1,
    image: "https://source.unsplash.com/random?query=geography&count=1",
    address: "San Francisco, CA",
    country: "United States",
    distance_from_center: "100",
    num_of_beds: "2",
    check_in: "2020-01-01",
    check_out: "2020-01-02",
    status: "Pending",
    description: booking_desc,
  },
  {
    id: 2,
    image: "https://source.unsplash.com/random?query=geography&count=2",
    address: "Massachusetts, MA",
    country: "United States",
    distance_from_center: "200",
    num_of_beds: "3",
    check_in: "2020-01-01",
    check_out: "2020-01-02",
    status: "Accepted",
    description: booking_desc,
  },
  {
    id: 4,
    image: "https://source.unsplash.com/random?query=geography&count=4",
    address: "San Francisco, CA",
    country: "United States",
    distance_from_center: "100",
    num_of_beds: "2",
    check_in: "2020-01-01",
    check_out: "2020-01-02",
    status: "Rejected",
    description: booking_desc,
  },
  {
    id: 3,
    image: "https://source.unsplash.com/random?query=geography&count=3",
    address: "San Francisco, CA",
    country: "United States",
    distance_from_center: "100",
    num_of_beds: "2",
    check_in: "2020-01-01",
    check_out: "2020-01-02",
    status: "Pending",
    description: booking_desc,
  },
  {
    id: 5,
    image: "https://source.unsplash.com/random?query=geography&count=5",
    address: "Miami, FL",
    country: "United States",
    distance_from_center: "500",
    num_of_beds: "1",
    check_in: "2022-01-01",
    check_out: "2022-01-02",
    status: "Pending",
    description: booking_desc,
  },
  {
    id: 6,
    image: "https://source.unsplash.com/random?query=geography&count=6",
    address: "Texas, TX",
    country: "United States",
    distance_from_center: "1000",
    num_of_beds: "3",
    check_in: "2022-01-01",
    check_out: "2022-01-02",
    status: "Rejected",
    description: booking_desc,
  },
];
